{ ... }:
{
  vim = {
    keymaps = [
      {
        key = "<c-l>";
        mode = "i";
        silent = true;
        # See https://castel.dev/post/lecture-notes-1/#correcting-spelling-mistakes-on-the-fly
        action = "<c-g>u<Esc>[s1z=`]i<c-g>u";
      }
      {
        key = "<c-j>";
        mode = [
          "i"
          "n"
        ];
        silent = true;
        action = "<Esc>mz[sea";
      }
      {
        key = "<c-k>";
        mode = [
          "i"
          "n"
        ];
        silent = true;
        action = "<Esc>mz]sea";
      }
      {
        key = "<c-h>";
        mode = [
          "i"
          "n"
        ];
        silent = true;
        action = "<Esc>`za";
      }
    ];
    spellcheck = {
      enable = true;
      # List of mathematical words
      extraSpellWords."en.utf-8" = [
        "abelian"
        "adjoint"
        "adjugate"
        "affine"
        "analytic"
        "argand"
        "asymptotic"
        "autocorrelation"
        "autonomous"
        "basis"
        "bijection"
        "bijectivity"
        "bijects"
        "bolzano"
        "cardinality"
        "categorical"
        "cauchy"
        "codomain"
        "commutator"
        "contrapositive"
        "coprime"
        "coset"
        "cosets"
        "covariance"
        "cumulant"
        "curvature"
        "del"
        "delta"
        "densities"
        "derivable"
        "diagonalisable"
        "diagonalisation"
        "diffeomorphic"
        "diffeomorphism"
        "differentiable"
        "dirichlet"
        "disjoint"
        "eigenfunction"
        "eigenspace"
        "eigenspaces"
        "eigenvalue"
        "eigenvector"
        "endomorphic"
        "endomorphism"
        "epimorphic"
        "epimorphism"
        "equidimensional"
        "ergodic"
        "expectation"
        "extremum"
        "fibration"
        "fieldaxiom"
        "frechet"
        "frobenius"
        "functor"
        "gaussian"
        "generators"
        "grad"
        "gradient"
        "groupoid"
        "hamiltonian"
        "hausdorff"
        "hermitian"
        "holomorphic"
        "homeomorphic"
        "homeomorphism"
        "homomorphic"
        "homomorphism"
        "homotopy"
        "hyperbolic"
        "hyperplane"
        "hypersurface"
        "idempotent"
        "incongruent"
        "independent"
        "indicial"
        "infimum"
        "injective"
        "injectivity"
        "integrable"
        "invertible"
        "irreducible"
        "irrotational"
        "isocline"
        "isoclines"
        "isometries"
        "isometry"
        "isomorphic"
        "isomorphism"
        "jacobian"
        "kernel"
        "kronecker"
        "lagrangian"
        "laplacian"
        "lebesgue"
        "linearity"
        "linearly"
        "lipschitz"
        "manifold"
        "martingale"
        "measurable"
        "Minkowski"
        "monodromy"
        "monoid"
        "morphism"
        "multivariate"
        "nilpotent"
        "noetherian"
        "normalizer"
        "orthogonal"
        "orthonormal"
        "parametric"
        "pathwise"
        "permutation"
        "piecewise"
        "planarity"
        "polytope"
        "preimage"
        "primitive"
        "probabilistic"
        "projection"
        "quadrature"
        "quasiconvex"
        "random"
        "recurrence"
        "relativistic"
        "resolvent"
        "reversibility"
        "riemann"
        "rng"
        "scalar"
        "schur"
        "separable"
        "spectral"
        "spectrum"
        "stationary"
        "stochastic"
        "subadditive"
        "subgroup"
        "submanifold"
        "subset"
        "subsequences"
        "subspace"
        "supremum"
        "surjection"
        "surjectivity"
        "surjects"
        "symplectic"
        "tangential"
        "taylor"
        "topology"
        "totient"
        "transcendental"
        "transition"
        "transpose"
        "ultrafilter"
        "unitary"
        "variational"
        "vectorial"
        "wellordered"
        "WLOG"
        "Wronskian"
        "zorn"
      ];
    };
  };
}
